theme: jekyll-theme-cayman
title: Systematic Review and Meta-analysis Workshop
description: This page contains resources for the workshop to be held on July 8, 2021. Please note that it is still a work in-progress.

github:
  is_project_page: false

